### ISSUE TITLE
Input file format

### ISSUE THREAD

**Issue by taylorreiter** [ay-lab/HiCnv#1]
Is it possible for you to describe the input file format more? I tried using the HiC-Pro pipeline unsuccessfully, but have mapped and filtered my reads using `bwa mem` and `samtools`. I would like to use these bam files as input to your pipeline, but I don't know the input file format well enough to grasp whether this will work with your tool or not.

**Comment by ay-lab** [comment]
Hi,

In case of HiC-Pro you would have generated two bam files for a sample with following names

sample_R1_hg19.bwt2merged.bam and sample_R2_hg19.bwt2merged.bam. 

Here R1 and R2 refer to the two paired-end alignment files of the sample.

Following is an example output from one of the bam file.

DF9F08P1:236:C2RMYACXX:1:1101:1343:98777        0       chr4    25809265        42      50M     *       0       0       AGTACCCGTGGACCCGAGCTTTGTAGGCTCAGAGGAGGAAGAGACTCCAA      @C@FFFFFDHHHHJJJGGGGGIIHIIIJJJJI@FIJIIGGG2CCHICHGI      AS:i:0  XN:i:0  XM:i:0  XO:i:0  XG:i:0NM:i:0   MD:Z:50 YT:Z:UU RG:Z:BMG

If you can generate these two paired-end bam files using your custom script, you can run HiCnv from "Read_coverage_generation" step. 

All these pre HiCnv calling steps are required to generate two files 1. sample.perREfragStats and 2. sample.F_GC_MAP.bed.

The content of sample.perREfragStats file looks like the following 

chr1    0       16007   58      0       14      15      25      1       0       17      25

Field description:

1: chromosome 
2: Restriction fragment start
3: Restriction fragment end
4: Overall mapped pairs
5: Intra valid pairs
6: Inter valid pairs
7: All valid pairs
8: pairs removed due to distance
9: pairs removed due to dangling ends
10: pairs removed due to self-circle
11: pairs removed due to singletons
12: pairs removed due to dump

sample.F_GC_MAP.bed file looks like this

chr1    0       16007   0.656   0.310   16007   58

Field description:

1: chromosome 
2: Restriction fragment start
3: Restriction fragment end
4: mean GC content of start+500bp and end-500bp RE fragments.
5. mean mappability of the same region
6: RE fragment length
7: Overall mapped pairs  

All fields are separated by tabs.

If you can generate this sample.perREfragStats and sample.F_GC_MAP.bed file then you can directly run "run_HiCnv.pl" script under "CNV_calling" folder.

**Comment by taylorreiter** [comment]
Thank you!
